{{- $services := .Values.service.services }}
{{- range $name, $cfg := $services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  labels:
    {{- include "tycho-api.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $cfg.port }}
      targetPort: {{ $cfg.port }}
      protocol: TCP
      name: {{ $name }}
  selector:
    app: "tycho-api"
    chain: {{ $name | quote }}
{{- end }}
