services:
  # Ethereum Mainnet Tycho API
  tycho-api-ethereum:
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: tycho-explorer/api:latest
    container_name: tycho-api-ethereum
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "3001:3000"
    environment:
      TYCHO_API_KEY: ${TYCHO_API_KEY}
      RUST_LOG: ${RUST_LOG:-info}
    command: ["/usr/local/bin/tycho-api", "--tvl-threshold", "${TVL_THRESHOLD}", "--chain", "ethereum", "--port", "3000", "--tycho-url", "${TYCHO_ETHEREUM_URL}"]
    networks:
      - tycho-network
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://localhost:3000/ || (echo '🔴 [HEALTH] Ethereum API health check failed' && exit 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.swift.service=tycho-api"
      - "com.swift.chain=ethereum"
  
  # Base Mainnet Tycho API
  # All services use the SAME image
  tycho-api-base:
    image: tycho-explorer/api:latest
    container_name: tycho-api-base
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "3002:3000"
    environment:
      TYCHO_API_KEY: ${TYCHO_API_KEY}
      RUST_LOG: ${RUST_LOG:-info}
    command: ["/usr/local/bin/tycho-api", "--tvl-threshold", "${TVL_THRESHOLD}", "--chain", "base", "--port", "3000", "--tycho-url", "${TYCHO_BASE_URL}"]
    networks:
      - tycho-network
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://localhost:3000/ || (echo '🔴 [HEALTH] Base API health check failed' && exit 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.swift.service=tycho-api"
      - "com.swift.chain=base"
  
  # Unichain Mainnet Tycho API
  # All services use the SAME image
  tycho-api-unichain:
    image: tycho-explorer/api:latest
    container_name: tycho-api-unichain
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "3003:3000"
    environment:
      TYCHO_API_KEY: ${TYCHO_API_KEY}
      RUST_LOG: ${RUST_LOG:-info}
    command: ["/usr/local/bin/tycho-api", "--tvl-threshold", "${TVL_THRESHOLD}", "--chain", "unichain", "--port", "3000", "--tycho-url", "${TYCHO_UNICHAIN_URL}"]
    networks:
      - tycho-network
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://localhost:3000/ || (echo '🔴 [HEALTH] Unichain API health check failed' && exit 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.swift.service=tycho-api"
      - "com.swift.chain=unichain"
  
  # Frontend Application
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_PROGRESS=plain
        - VITE_WEBSOCKET_URL_ETHEREUM=${VITE_WEBSOCKET_URL_ETHEREUM}
        - VITE_WEBSOCKET_URL_BASE=${VITE_WEBSOCKET_URL_BASE}
        - VITE_WEBSOCKET_URL_UNICHAIN=${VITE_WEBSOCKET_URL_UNICHAIN}
        - VITE_API_ETHEREUM_URL=${VITE_API_ETHEREUM_URL}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_API_UNICHAIN_URL=${VITE_API_UNICHAIN_URL}
    container_name: tycho-explorer-frontend
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - "8080:80"
    depends_on:
      tycho-api-ethereum:
        condition: service_healthy
      tycho-api-base:
        condition: service_healthy
      tycho-api-unichain:
        condition: service_healthy
    environment:
      VITE_WEBSOCKET_URL_ETHEREUM: ${VITE_WEBSOCKET_URL_ETHEREUM}
      VITE_WEBSOCKET_URL_BASE: ${VITE_WEBSOCKET_URL_BASE}
      VITE_WEBSOCKET_URL_UNICHAIN: ${VITE_WEBSOCKET_URL_UNICHAIN}
      VITE_API_ETHEREUM_URL: ${VITE_API_ETHEREUM_URL}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_API_UNICHAIN_URL: ${VITE_API_UNICHAIN_URL}
    networks:
      - tycho-network
    labels:
      - "com.swift.service=frontend"

networks:
  tycho-network:
    driver: bridge
    driver_opts:
      com.docker.network.debug: "true"