apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen       8080;
      server_name  localhost;
      root /usr/share/nginx/html;
      index index.html;

      # REST API endpoints for each chain
      location /ethereum/ {
          proxy_pass http://tycho-api-ethereum:3001/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /base/ {
          proxy_pass http://tycho-api-base:3002/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /unichain/ {
          proxy_pass http://tycho-api-unichain:3003/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
          try_files $uri $uri/ /index.html;
      }
      # Enable gzip compression
      gzip on;
      gzip_types text/plain text/css text/javascript application/javascript application/json;
    }
